
### GET request to example server
GET http://localhost:3000/animals

###

### GET request to example server


GET http://localhost:3000/animals/2

###

### delete request to example server
DELETE http://localhost:3000/animals/3

###

### delete request to example server
PUT http://localhost:3000/animals/3
Content-Type: application/json

{
    "name": "Dawid",
    "species": "Sigma",
    "age": 12,
    "isEndangered": "True",
    "habitat": "Polska"
}

###